Chore: Hide New Read-Only TAP Admin Field
mbta/reduced_fares pull request #297
Opened 2023-03-24 21:40 UTC by krisrjohnson21

This PR adds a new read-only field to the Admin Review stage of the TAP application. This new field prevents Admin from submitting an application without completing the required fields, but only if the application is approved.

2023-03-28 14:19 UTC, krisrjohnson21 commented
@karenhawkinson thanks for the guidance! It's been a minute since I had to make CSS changes 🙂 I think it's done correctly now

2023-03-31 13:59 UTC, karenhawkinson requested changes
@krisrjohnson21 this looks great! One tiny edit to a field number is needed (due to recent my recent changes to the TAP form).

2023-03-31 13:59 UTC, karenhawkinson commented on build/stylesheets/admin-tap.css
> +#form-element-wrapper_217,
When I refactored the TAP form, I deleted field 265 thinking it wasn't needed, and ended up replacing it with field 275. Please update the code to match.

#form-element-wrapper_217,
#form-element-wrapper_271,
#form-element-wrapper_275 {
  visibility: hidden;
  height: 0;
  margin: -20px 0;
}

2023-03-31 17:10 UTC, karenhawkinson approved these changes
@krisrjohnson21 looks great!

2023-03-31 17:27 UTC, merged